import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
const labels={in_progress:'En cours',not_started:'À démarrer',blocked:'En attente',passed:'Recette réussie'};

export async function renderParcours(root) {
  const plan=JSON.parse(await readFile(resolve(root,'data/parcours-mise-en-ligne.json'),'utf8'));
  const ids=['initialisation','recette-locale','recette-preproduction','mise-en-production'];
  if(!Array.isArray(plan.stages)||plan.stages.length!==4||plan.stages.some((stage,index)=>stage.id!==ids[index]||!labels[stage.status]||!Array.isArray(stage.evidence)||!Array.isArray(stage.remaining)))throw new Error('Parcours de mise en ligne invalide.');
  const stages=plan.stages.map((stage,index)=>`<section class="step"><div class="step-head"><span class="number">${index+1}</span><div><h2>${escapeHtml(stage.title)}</h2><span class="state">${labels[stage.status]}</span></div></div><p>${escapeHtml(stage.action)}</p><h3>Constats</h3>${stage.evidence.length?`<ul>${stage.evidence.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul>`:'<p>Pas encore de résultat pour cette étape.</p>'}<h3>À faire ou à confirmer</h3><ul>${stage.remaining.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul></section>`).join('');
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>TC Longages · Mise en ligne V1</title><style>*{box-sizing:border-box}body{margin:0;background:#f6f3f1;color:#282226;font:16px/1.55 system-ui,sans-serif}header{background:#8b142a;color:white;padding:34px max(20px,calc((100vw - 1020px)/2))}h1{margin:5px 0 10px;font-size:clamp(1.7rem,4vw,2.5rem)}h2{margin:0;font-size:1.35rem}h3{font-size:1rem;margin:18px 0 3px}p{max-width:75ch}a{color:#8b142a}header a{color:white}main{max-width:1060px;margin:25px auto;padding:0 20px}.scope,.step{background:white;border:1px solid #e1d7d5;border-radius:12px;padding:22px;margin:16px 0}.scope{border-left:5px solid #a61b33}.step-head{display:flex;gap:13px;align-items:center}.number{width:38px;height:38px;flex:none;border-radius:50%;background:#a61b33;color:white;display:grid;place-items:center;font-weight:700}.state{display:inline-block;background:#f0e1e4;padding:3px 8px;border-radius:5px;margin-top:4px;font-size:.88rem}li{margin:6px 0}footer{max-width:1060px;margin:auto;padding:15px 20px 35px;color:#68585b}@media(min-width:800px){.steps{display:grid;grid-template-columns:1fr 1fr;gap:15px}.step{margin:0}}:focus-visible{outline:3px solid #2453aa;outline-offset:3px}</style></head><body><header><small>TENNIS CLUB DE LONGAGES · SUIVI LOCAL</small><h1>Mise en ligne de la V1</h1><p>Quatre étapes pour préparer et vérifier le site public du club.</p></header><main><section class="scope"><strong>Périmètre :</strong> ${escapeHtml(plan.scope)}<p>Production : <strong>${escapeHtml(plan.productionHost)}</strong> · Préproduction : <strong>${escapeHtml(plan.preproductionHost)}</strong></p><p><strong>État réel :</strong> ${plan.productionDeploymentExecuted?'Livraison exécutée':'Aucune livraison en production exécutée'} ; ${plan.publicOpeningExecuted?'ouverture publique exécutée':'aucune ouverture publique exécutée'}.</p><p>Ce tableau est en lecture seule. Les décisions déjà enregistrées restent dans le <a href="/historique">suivi historique des phases</a>.</p></section><div class="steps">${stages}</div></main><footer>Actualisez la page pour voir le dernier état enregistré. Aucun bouton ici ne modifie l’hébergement ou ne publie le site.</footer></body></html>`;
}
