const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { mkdir, writeFile, readFile } = require('node:fs/promises');
const path = require('node:path');
(async () => {
  const { createDemoServer } = await import('./demo-server.mjs');
  const server = createDemoServer();
  await new Promise(resolve => server.listen(0,'127.0.0.1',resolve));
  const origin = `http://127.0.0.1:${server.address().port}`;
  const browser = await chromium.launch({ channel:'chrome', headless:true });
  const context = await browser.newContext({ viewport:{width:1440,height:1000}, acceptDownloads:true });
  const page = await context.newPage();
  const errors = [], external = [], checks = [];
  const output = path.resolve(__dirname,'../docs/recette/demo');
  await mkdir(output,{recursive:true});
  page.on('pageerror',error=>errors.push(error.message));
  context.on('request',request=>{if(!request.url().startsWith(origin+'/')&&!request.url().startsWith('data:'))external.push(request.url());});
  page.on('dialog',dialog=>dialog.accept());
  try {
    await page.goto(origin+'/');
    await page.screenshot({path:path.join(output,'parcours-bureau.png'),fullPage:true});
    assert.equal(await page.locator('.tour-card').count(),6);
    checks.push('Visite guidée et liens vers toutes les pages');
    await page.goto(origin+'/adherer.html');
    await page.locator('#next-step').click();
    assert.equal(await page.locator('#form-error').isVisible(),true);
    await page.locator('#example-adult').click();
    await page.screenshot({path:path.join(output,'formulaire-bureau.png'),fullPage:true});
    for(let i=0;i<4;i++) await page.locator('#next-step').click();
    await page.locator('#confirm-fiction').check();
    await page.locator('#next-step').click();
    const adultId = await page.locator('#success-reference').textContent();
    await page.locator('#success-bureau-link').click();
    assert.ok(await page.locator('#dossier-detail').innerText().then(x=>x.includes(adultId)));
    assert.equal(await page.evaluate(id=>TCLDemo.all().find(x=>x.id===id).training,adultId),false);
    await page.getByRole('button',{name:'Finaliser le dossier fictif',exact:true}).click();
    await page.locator('#dialog-confirm').click();
    await page.waitForFunction(id=>TCLDemo.all().find(x=>x.id===id).status==='finalise',adultId);
    checks.push('Adulte sans cours : dépôt fictif, continuité bureau et finalisation confirmée');
    await page.goto(origin+'/adherer.html');
    await page.locator('#example-child').click();
    for(let i=0;i<4;i++) await page.locator('#next-step').click();
    await page.locator('#confirm-fiction').check();
    await page.locator('#next-step').click();
    const childId = await page.locator('#success-reference').textContent();
    await page.locator('#success-bureau-link').click();
    assert.equal(await page.getByRole('button',{name:'Finaliser le dossier fictif',exact:true}).isDisabled(),true);
    await page.locator('#dossier-group').selectOption('g-ex-jeunes');
    await page.getByRole('button',{name:'Confirmer le choix du groupe',exact:true}).click();
    await page.locator('#dialog-confirm').click();
    await page.waitForFunction(id=>TCLDemo.all().find(x=>x.id===id).groupId==='g-ex-jeunes',childId);
    checks.push('Mineur : responsable, disponibilités et affectation manuelle compatible');
    await page.screenshot({path:path.join(output,'inscriptions-bureau.png'),fullPage:true});
    await page.locator('#tab-disponibilites').click();
    assert.ok(await page.locator('#availability-table').innerText().then(x=>x.includes('Préféré')));
    await page.locator('#tab-groupes').click();
    assert.ok(await page.locator('#group-list').innerText().then(x=>x.includes('Lou')));
    await page.locator('#tab-echanges').click();
    const before = await page.evaluate(()=>TCLDemo.all().length);
    await page.locator('#simulate-import').click();
    assert.equal(await page.evaluate(()=>TCLDemo.all().length),before);
    assert.match(await page.locator('#import-rows').innerText(),/Doublon/);
    await page.locator('#confirm-import').click();
    await page.locator('#dialog-confirm').click();
    await page.waitForFunction(n=>TCLDemo.all().length===n+1,before);
    await page.locator('#simulate-import').click();
    assert.equal(await page.locator('#confirm-import').isDisabled(),true);
    const downloadEvent = page.waitForEvent('download');
    await page.locator('#export-csv').click();
    const download = await downloadEvent;
    assert.match(download.suggestedFilename(),/\.csv$/);
    const csv = await readFile(await download.path(),'utf8');
    assert.match(csv,/Exemple-Import/);
    checks.push('Import simulé sans lecture de fichier : aperçu, confirmation, doublon refusé ; CSV fictif téléchargé');
    await page.screenshot({path:path.join(output,'echanges-bureau.png'),fullPage:true});
    await page.goto(origin+'/communication.html');
    await page.evaluate(()=>{window.__opens=0;window.__copies=0;window.open=()=>{window.__opens++;};Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{window.__copies++;}}});});
    assert.equal(await page.locator('#import-posts').isDisabled(),true);
    await page.locator('#post-list button').first().click();
    await page.locator('#review-post').click();
    await page.locator('#confirm-approval').click();
    await page.locator('#share-whatsapp').click();
    await page.locator('#copy-whatsapp').click();
    assert.deepEqual(await page.evaluate(()=>[window.__opens,window.__copies]),[0,0]);
    assert.equal(await page.evaluate(()=>localStorage.getItem('tcl.communication.v1')),null);
    await page.goto(origin+'/actualites-bureau.html');
    assert.match(await page.locator('body').innerText(),/Bienvenue dans la démonstration/);
    checks.push('Communication isolée : validation et aperçu ; WhatsApp et copie sans effet externe');
    for(const width of [390,320]) {
      await page.setViewportSize({width,height:844});
      for(const name of ['parcours','index','adherer','bureau','inscriptions','communication','actualites-bureau']) {
        await page.goto(origin+'/'+name+'.html');
        assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,`${name} à ${width}px`);
        if(width===390&&['parcours','adherer','inscriptions'].includes(name)) await page.screenshot({path:path.join(output,name+'-mobile.png'),fullPage:true});
      }
    }
    checks.push('Sept pages sans débordement horizontal à 390 et 320 px');
    assert.deepEqual(errors,[]); assert.deepEqual(external,[]);
    checks.push('Aucune erreur JavaScript et aucun appel réseau externe');
    await writeFile(path.join(output,'results.json'),JSON.stringify({date:new Date().toISOString(),status:'passed',scope:'Démonstration isolée, données fictives et serveur éphémère',checks},null,2));
    console.log(JSON.stringify({status:'passed',checks,errors,external},null,2));
  } finally { await browser.close(); server.closeAllConnections(); await new Promise(resolve=>server.close(resolve)); }
})().catch(error=>{console.error(error);process.exitCode=1;});
